version: '2'
services:
    babelbot:
        build:
            context: ./
        env_file:
            - ./my.env
        volumes:
            - ./app:/go/src/github.com/user/myProject/app
        ports:
            - 3000:3000
        container_name: babelbot
        command: gin -i run main.go
        environment:
            - PORT=6969
        env_file:
            - ./.env
    db:
        image: mysql:5.7
        env_file:
            - ./.env
